# Generated by Django 2.1.2 on 2018-11-03 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 21, 29, 11, 818036, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
